### ISSUE TITLE
Cooldown for mapvotes

### ISSUE THREAD

**Issue by Igce4** [jxsl13/zcatch#30]
When someone votes for a new map to play, a lot of the time people instantly reverse vote for the previous map. Then they vote for the new map again, it ends up in an endless loop and eventually people will try to kickvote other players. To avoid this, I suggest a mapvote cooldown of around 10 minutes for everybody after a mapvote succeeded.

**Comment by jxsl13** [comment]
after a map has been successfully changed, the players are forced to play it for at least 5 minutes before changing it back, making them think twice before they start a map change vote. This time is adjustable. I find 10 minutes too much, especially when people simply don't like the map(without any bad intent) want to change the map to a different one.
