### ISSUE TITLE
Joining issue on too many players

### ISSUE THREAD

**Issue by AssassinTee** [jxsl13/zcatch#50]
People sometimes can't join when the server *was* full and now space is avaible!
Happened to me, you have to rejoin to join the game.

People who join spec automatically when the server is full DON'T ADD to the top players caught people, making it possible to rejoin even when you are caught and thus you have to rekill players.

These are two bugs <.<

**Comment by jxsl13** [comment]
Players that join while the server is full, 16 player, are added to the spectators and can join any time.

People joining while there are less than 16 players ingame are more or less randomly added to one of the dominating players. #49 Might solve this second part.

**Comment by jxsl13** [comment]
hm, I wonder why the 16th player cannot join currently, maybe the vpn detection might take part in doing that, as it's connected via econ.

**Comment by jxsl13** [comment]
apparently not.

The rejoin issue has been kinda fixed by caching ips for one minute.

**Comment by jxsl13** [comment]
in testing. should be fixed.
