### ISSUE TITLE
mac osx 10.11 error

### ISSUE THREAD

**Issue by M0REKZ** [jxsl13/zcatch#67]
when i try to open this program i see this error (modified copypaste for username):

`KZ:~ username$ /Users/username/Library/Application\ Support/Steam/steamapps/common/Teeworlds/tw/zCatch_srv ; exit;
dyld: Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /Users/username/Library/Application Support/Steam/steamapps/common/Teeworlds/tw/zCatch_srv
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/username/Library/Application Support/Steam/steamapps/common/Teeworlds/tw/zCatch_srv
Trace/BPT trap: 5
logout
Saving session...
...blah blah bla...

[finished process]`

**Comment by jxsl13** [comment]
try the precompiled version:

https://github.com/jxsl13/zcatch/actions/runs/43920372

**Comment by jxsl13** [comment]
and paste the full log, that might help.

**Comment by jxsl13** [comment]
might be missing gcc or clang, try installing xcode.

**Comment by jxsl13** [comment]
your macOS version was released 2015, it does not support the required C++17 standard that is used in this mod. you might want to install brew and a newer GCC compiler instead of the older clang version that is likely to be running on your machine.

**Comment by M0REKZ** [comment]
>  try the precompiled version:
> https://github.com/jxsl13/zcatch/actions/runs/43920372`


At the moment that version works, you should replace the version found in https://github.com/jxsl13/zcatch/releases
