### ISSUE TITLE
Rank arguments not supported by new chat commands

### ISSUE THREAD

**Issue by ChillerDragon** [jxsl13/zcatch#69]
With a newer client typing ``/rank foo`` will result in sending the chat message ``foo`` not showing foo's rank.

**Comment by maximyurchuk** [comment]
I can't reproduce such behaviour, but I believe it will be fixed after #82 will be merged. Maybe you checked on some non-release version between 0.7.4 and 0.7.5.

**Comment by ChillerDragon** [comment]
@maximyurchuk yes thanks for the reminder I can confirm it is now fixed (tested on current vanilla master).
