### ISSUE TITLE
/help hair

### ISSUE THREAD

**Issue by jxsl13** [jxsl13/zcatch#74]
the golden rule of zCatch needs to be incorperated into the mod.

basically explaining to people, why they will not win a round unless their Tee has either hair or an hair ornament like twinbops.

Golden rule of zCatch: No Hair, No Win.

**Comment by ChillerDragon** [comment]
Never heard about this rule but now that I think about it it makes a lot of sense. That would also explain why I slap away all the noobs in zCatch easily because I have big hair!

**Comment by jxsl13** [comment]
easter egg maybe
