### ISSUE TITLE
RFC: proper econ logging

### ISSUE THREAD

**Issue by jxsl13** [jxsl13/zcatch#86]
The current system is broken and does not allow for a proper tracking of joining/leaving players.
Especially map changes break the nickname/IP association.

A joining player's data must be completely contained within **one** econ line.
It **must** not be split across multiple lines.

Data that should be visible on join should be: 
- ID
- Nickname (max 20 characters)
- Clan (max 16 characters)
- IP 
- Country Flag (2-3 characters abbreviation)

What level should those join/leave messages be displayed on? 
- game?
- server?
- engine?

Map changes should allow to reset your current server representation (Econ parsing tools)
because a player can disconnect from the server in the middle of the new map's download.

Does a map change currently show any special logging output that can be parsed?

Chat Messages should comply to a backwards compatible format that, which I proposed in Vanilla in order to differentiate team chat messages, whisper messages and public chat messages.

**Comment by jxsl13** [comment]
Remove the weird(I don't know where the hell that came from) 
'OldNickname' -> 'TrimmerdNickname' that does not help to properly parse the Econ logging.

**Comment by maximyurchuk** [comment]
What is "econ"?

**Comment by jxsl13** [comment]
Econ is an external rcon(f2) console that can be accessed using telnet without having to be on the server.

**Comment by jxsl13** [comment]
https://www.teeworlds.com/?page=docs&wiki=server_settings

server settings prefixed with `ec_` allow the configuration of the external console (econ)

**Comment by jxsl13** [comment]
I'm using that for my server moderation tools that connect to the zCatch servers via the external console and allow to see chat, votes etc. in discord. 
https://github.com/jxsl13/TeeworldsEconDiscordModerationBot

I am intending to make it possible to represent the current server state by simply parsing the econ log.
Player/IP association, Nickname, Clan/Flag, Kills/Deaths etc.
