### ISSUE TITLE
"/version" chat command

### ISSUE THREAD

**Issue by maximyurchuk** [jxsl13/zcatch#88]
I think there can be added "/version" command in chat commands to determine version of a server. 

Git hash can be good candidate for version, moreover it [already accessable](https://github.com/jxsl13/zcatch/blob/zCatch-0.7.x/src/test/git_revision.cpp) from C++ code. 

Code, which handles commands [here](https://github.com/jxsl13/zcatch/blob/1154b6480146133e6331524b4c424bb9985a4330/src/game/server/gamemodes/zcatch.cpp#L163).

**Comment by jxsl13** [comment]
I don't mind, but  should be zCatch server version(revision tag, v0.3.5), git hash and Teeworlds main version(0.7.5) if that's possible.

**Comment by jxsl13** [comment]
maybe 
`zCatch 0.7.5 <git hash>` for not released versions.
and
`zCatch 0.7.5 v0.3.5` for released versions.
?

**Comment by maximyurchuk** [comment]
Server version (`0.7.5`) is already known from Teeworlds GUI, so i think its not needed. Also imho, it meaningless, because this is [just number](https://github.com/jxsl13/zcatch/commit/b8847759e312d22fd528f6d75e93142004b2de4a) without merging new commits from Teeworlds repo.

The problem that I want to solve is to determine which version of the source code is running on public servers, so, git commit looks suitably. Revision tag (`v0.3.5`) can be added too, but its secondary and harder to implement, I think.

**Comment by jxsl13** [comment]
the revision tag for released versions would be great.
I don't touch that topic because I did not think about that at all.

**Comment by maximyurchuk** [comment]
It's because you deploy and know which version is running on servers. Other people don't know (but it can be intersting for them, especially for contributors).

**Comment by jxsl13** [comment]
makes sense

**Comment by jxsl13** [comment]
I think the 0.7.5 In the Teeworlds f1 GUI refers to the client version?
Where do you see the server version 0.7.5?

**Comment by maximyurchuk** [comment]
When your see a list of available servers, the server version is also displayed.

**Comment by jxsl13** [comment]
ok
